// ContosoPizza.http was not part of the original setup, the following is made by me in an attempt to follow the instructions
### Base URL for ContosoPizza API
@baseUrl = https://localhost:5001


//this section has been delected an replaced with items from the instructions

### The Following will be from the instructions

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

### Create a new pizza using the API
POST @baseUrl/pizza
Content-Type: application/json
{
    "name": "Sample Pizza",
    "isGlutenFree": false
}

### Update a pizza using the API
PUT @baseUrl/pizza/{{id}}
Content-Type: application/json
{
    "name": "Updated Pizza Name",
    "isGlutenFree": true
}

### Update a pizza using the API with HttpPut
PUT @baseUrl/pizza/{{id}}
Content-Type: application/json
{
    "id": 1,
    "name": "Updated Pizza Name",
    "isGlutenFree": true
}

### Delete a pizza using the API
DELETE @baseUrl/pizza/{{id}
}

